[package]
name = "macaw"
version = "0.1.0"
authors = [ "Michel Meyer <michel@zazabe.fr>", "Reto" ]
edition = "2024"

[lib]
name = "macaw"
path = "lib/lib.rs"

[[bin]]
name = "macaw"
path = "bin/macaw.rs"

[[example]]
name = "http_proxy"
path = "examples/http_proxy.rs"

[dependencies]
rustls = "0.23"
rustls-platform-verifier = "0.6"
tokio = { version = "1", features = [ "full" ] }
bytes = "1.2"
http = "1"
http-body-util = "0.1"
pin-project-lite = "0.2"
structopt = "0.3"
anyhow = "1"
hyper = { version = "1", features = [ "full" ] }
hyper-util = { version = "0.1", features = [ "full" ] }
hyper-rustls = { version = "0.27", features = [ "http1", "http2", "rustls-platform-verifier" ] }
log = "0.4"
env_logger = "0.11"
tracing = "*"
tracing-subscriber = { version = "^0.3.16", features = [ "env-filter" ] }
