[workspace]
members = [ "macaw-core", "macaw-http", "macaw-ws" ]

[workspace.package]
version = "0.1.0"
authors = [ "Michel Meyer <michel@zazabe.fr>", "Reto" ]
edition = "2024"

[workspace.dependencies]
anyhow = "1"
arrayvec = { version = "0.7", features = [ "serde" ] }
async-trait = "0.1.85"
async-stream = "0.3.5"
base64 = "0.22"
bytes = "1.2"
chrono = { version = "0.4", features = [ "serde" ] }
dyn-clone = "1.0.17"
dyn-clonable = "0.9.0"
env_logger = "0.11"
futures = "0.3"
http = "1"
http-body-util = "0.1"
hyper = { version = "1", features = [ "full" ] }
hyper-rustls = { version = "0.27", features = [ "http1", "http2", "rustls-platform-verifier" ] }
hyper-util = { version = "0.1", features = [ "full" ] }
itertools = "0.14"
log = "0.4"
pin-project-lite = "0.2"
rustls = "0.23"
rustls-platform-verifier = "0.6"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
serde_yaml = "0.9"
structopt = "0.3"
tokio = { version = "1", features = [ "full" ] }
tokio-tungstenite = { version = "0.28", features = [ "url", "rustls-tls-native-roots" ] }
tokio-stream = { version = "0.1", features = [ "full" ] }
tracing = "*"
tracing-subscriber = { version = "^0.3.16", features = [ "env-filter" ] }
typetag = "0.2.21"
url = "2.5.2"
uuid = { version = "1.13", features = [ "v4", "serde" ] }

[workspace.lints.rust]
dead_code = "allow"
unused_variables = "allow"
unused_imports = "allow"

[workspace.lints.clippy]
match_single_binding = "allow"

[package]
name = "macaw"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "macaw"
path = "lib/lib.rs"

[[example]]
name = "recorder"
path = "examples/recorder.rs"

[[example]]
name = "replayer"
path = "examples/replayer.rs"

[dependencies]
macaw-core = { path = "macaw-core" }
macaw-http = { path = "macaw-http" }
macaw-ws = { path = "macaw-ws" }
anyhow.workspace = true
tokio.workspace = true
structopt.workspace = true
log.workspace = true
env_logger.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
serde_json.workspace = true
typetag.workspace = true
serde.workspace = true
