services:
  macaw:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace/macaw:cached
      - home-data:/home/dev:cached
    env_file:
      - .env
    networks:
      - macaw

networks:
  macaw:

volumes:
  home-data:
